export enum LocalizationKey {
    // onboarding 
    ONBOARDING_TITLE_1 = "onboarding-title-1",
    ONBOARDING_SUBTITLE_1 = "onboarding-subtitle-1",
    ONBOARDING_TITLE_2 = "onboarding-title-2",
    ONBOARDING_SUBTITLE_2 = "onboarding-subtitle-2",
    ONBOARDING_TITLE_3 = "onboarding-title-3",
    ONBOARDING_SUBTITLE_3 = "onboarding-subtitle-3",
    
    //login
    LOGIN_PASSWORD_PLACEHOLDER = "login-password-placeholder",
    LOGIN_FORGOT_PASSWORD = "login-forgot-password",
    LOGIN_BUTTON = "login-button",
    LOGIN_NO_ACCOUNT = "login-no-account",
    LOGIN_SIGNUP_LINK = "login-signup-link",
    LOGIN_EMAIL_EMPTY = "login-email-error",
    LOGIN_PASSWORD_EMPTY = "login-password-error",
    LOGIN_INVALID_CREDENTIALS = "login-invalid-credentials",
    LOGIN_TRY_AGAIN = "login-try-again",
    PASSWORD_MISMATCH = "password-mismatch",
    PASSWORD_CHANGE_SUCCESS = "password-change-success",
    CURRENT_PASSWORD = "current-password",
    NEW_PASSWORD = "new-password",
    CONFIRM_NEW_PASSWORD = "confirm-new-password",
    WANT_TO_GO_BACK = "want-to-go-back",
    GO_BACK = "go-back",
    SUCCESS = "success",
    NAME_REQUIRED = "name-required",
    REGISTRATION_SUCCESS = "registration-success",
    AGREEMENT_REQUIRED = "agreement-required",
    REGISTRATION_TERMS = "registration-terms",
    SIGN_UP = "sign-up",
    ALREADY_HAVE_ACCOUNT = "already-have-account",
    NOTIFY = "notify",
  // common
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",
  CONFIRM = "confirm",
  CANCEL = "cancel",
  CLEAR = "clear",

  // nav-related
  TRANSACTIONS = "transactions",
  WALLETS = "wallets",
  BUDGETS = "budgets",
  ADD = "add",

  // wallets
  CASH = "cash",
  CARD = "card",
  EWALLET = "ewallet",

  // categories
  ALL = "all",
  BILL = "bill",
  EDUCATION = "education",
  ENTERTAINMENT = "entertainment",
  FAMILY = "family",
  FOOD = "food",
  GIFT = "gift",
  HEALTH = "health",
  INSURANCE = "insurance",
  INVESTMENT = "investment",
  OUTGOING_TRANSFER = "outgoing-transfer",
  PAY_INTEREST = "pay-interest",
  SHOPPING = "shopping",
  TRANSPORTATION = "transportation",
  COLLECT_INTEREST = "collect-interest",
  INCOMING_TRANSFER = "incoming-transfer",
  SALARY = "salary",

  SELECT_WALLET = "select-wallet",
  SELECT_CATEGORY = "select-category",
  SELECT_WALLET_TYPE = "select-wallet-type",
  SELECT_PERIOD = "select-period",
  EXPENSE = "expense",
  INCOME = "income",
  AMOUNT = "amount",
  
  // budget-related
  TOTAL_BUDGET = "total-budget",
  TOTAL_SPENT = "total-spent",
  DAY = "day",
  DAYS = "days",
  REMAINING = "remaining",
  CREATE_BUDGET = "create-budget",
  LEFT = "left",
  CATEGORY = "category",
  SPENT = "spent",
  WALLET = "wallet",
  TIME = "time",
  THIS_WEEK = "this-week",
  THIS_MONTH = "this-month",
  THIS_YEAR = "this-year",
  TRANSACTION_LIST = "transaction-list",
  BUDGET_DETAILS = "budget-details",
  EDIT_BUDGET = "edit-budget",
  SAVE = "save",
  CAN_SPEND = "can-spend",
  OVERSPENT = "overspent",
  VIEW_FINISHED_BUDGETS = "view-finished-budgets",
  VIEW_RUNNING_BUDGETS = "view-running-budgets",

  WALLET_UNSELECTED = "wallet-unselected",
  CATEGORY_UNSELECTED = "category-unselected",
  ZERO_AMOUNT = "zero-amount",
  NOT_ENOUGH_MONEY = "not-enough-money",
  DELETE_CONFIRMATION = "delete-confirmation",

  // home
  CURRENT_BALANCE = "current-balance",
  TOTAL_INCOME = "total-income",
  TOTAL_EXPENSE = "total-expensse",
  SPENDING_REPORT = "spending-report",
  WEEK_EXPENSE = "week-expense",
  MONTH_EXPENSE = "month-expense",
  TOP_EXPENSE = "top-expense",
  RECENT_TRANSACTIONS = "recent-transaction",
  EDIT = "edit",
  DELETE = "delete",

  // wallet-related
  TRANSFER_MONEY = "transfer-money",
  FROM = "from",
  TO = "to",
  NOTE = "note",
  OPTIONS = "options",
  TODAY = "today",
  NAME = "name",
  TYPE = "type",
  BALANCE = "balance",
  ADD_NEW_WALLET = "add-new-wallet",

  // error messages
  ERROR_EMPTY = "error-empty",
}
