export enum LocalizationKey {
  // common
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",
  CONFIRM = "confirm",
  CANCEL = "cancel",
  CLEAR = "clear",

  // nav-related
  TRANSACTIONS = "transactions",
  WALLETS = "wallets",
  BUDGETS = "budgets",
  ADD = "add",

  // wallets
  CASH = "cash",
  CARD = "card",
  EWALLET = "ewallet",

  // categories
  ALL = "all",
  BILL = "bill",
  EDUCATION = "education",
  ENTERTAINMENT = "entertainment",
  FAMILY = "family",
  FOOD = "food",
  GIFT = "gift",
  HEALTH = "health",
  INSURANCE = "insurance",
  INVESTMENT = "investment",
  OUTGOING_TRANSFER = "outgoing-transfer",
  PAY_INTEREST = "pay-interest",
  SHOPPING = "shopping",
  TRANSPORTATION = "transportation",
  COLLECT_INTEREST = "collect-interest",
  INCOMING_TRANSFER = "incoming-transfer",
  SALARY = "salary",

  SELECT_WALLET = "select-wallet",
  SELECT_CATEGORY = "select-category",
  SELECT_WALLET_TYPE = "select-wallet-type",
  SELECT_PERIOD = "select-period",
  EXPENSE = "expense",
  INCOME = "income",
  AMOUNT = "amount",
  
  // budget-related
  TOTAL_BUDGET = "total-budget",
  TOTAL_SPENT = "total-spent",
  DAY = "day",
  DAYS = "days",
  REMAINING = "remaining",
  CREATE_BUDGET = "create-budget",
  LEFT = "left",
  CATEGORY = "category",
  SPENT = "spent",
  WALLET = "wallet",
  TIME = "time",
  THIS_WEEK = "this-week",
  THIS_MONTH = "this-month",
  THIS_YEAR = "this-year",
  TRANSACTION_LIST = "transaction-list",
  BUDGET_DETAILS = "budget-details",
  EDIT_BUDGET = "edit-budget",
  SAVE = "save",
  CAN_SPEND = "can-spend",
  OVERSPENT = "overspent",
  VIEW_FINISHED_BUDGETS = "view-finished-budgets",
  VIEW_RUNNING_BUDGETS = "view-running-budgets",

  WALLET_UNSELECTED = "wallet-unselected",
  CATEGORY_UNSELECTED = "category-unselected",
  ZERO_AMOUNT = "zero-amount",
  NOT_ENOUGH_MONEY = "not-enough-money",
  DELETE_CONFIRMATION = "delete-confirmation",

  // home
  CURRENT_BALANCE = "current-balance",
  TOTAL_INCOME = "total-income",
  TOTAL_EXPENSE = "total-expensse",
  SPENDING_REPORT = "spending-report",
  WEEK_EXPENSE = "week-expense",
  MONTH_EXPENSE = "month-expense",
  TOP_EXPENSE = "top-expense",
  RECENT_TRANSACTIONS = "recent-transaction",
  EDIT = "edit",
  DELETE = "delete",

  // settings
  ACCOUNT = "account",
  LANGUAGE = "language",
  ENGLISH = "english",
  VIETNAMESE = "vietnamese",
  CHANGE_LANGUAGE_EN = "change-language-en",
  CHANGE_LANGUAGE_VI = "change-language-vi",
  CHANGE_PASSWORD = "change-password",
  DELETE_ACCOUNT = "delete-account",
  DELETE_ACCOUNT_CONFIRM = "delete-account-confirm",

  // wallet-related
  TRANSFER_MONEY = "transfer-money",
  FROM = "from",
  TO = "to",
  NOTE = "note",
  OPTIONS = "options",
  TODAY = "today",
  NAME = "name",
  TYPE = "type",
  BALANCE = "balance",
  ADD_NEW_WALLET = "add-new-wallet",

  // error messages
  ERROR_EMPTY = "error-empty",
}
